= Gaboot!

:uri-kahoot: https://kahoot.com/
:uri-bespoke: http://markdalgleish.com/projects/bespoke.js
:uri-bundler: http://bundler.io
:uri-generator-bespoke: https://github.com/bespokejs/generator-bespoke
:uri-gulp: https://gulpjs.com
:uri-node: https://nodejs.org
:uri-nvm: https://github.com/creationix/nvm
:uri-ruby: https://www.ruby-lang.org
:uri-rvm: http://rvm.io

Educational Question-Maker Online Web App. Inspired by {uri-kahoot}[Kahoot].

Only for educational purposes.

[quote]
A {uri-bespoke}[Bespoke.js] presentation generated by {uri-generator-bespoke}[generator-bespoke].

== View slides locally

First, ensure you have install dependencies (if you ran the generator with the `--skip-install` switch):

 $ npm install

Finally, build and serve the presentation!

 $ npm run start-dev

You can view the presentation in your browser at the URL displayed in the console.

By default, the preview server runs on port 8080.
To change this default, you can assign a different number to the PORT environment variable:

Now you can build the presentation and publish it using:

 $ npm run build

The files in the [.path]_dist_ directory.
From there, they can be viewed in a browser from anywhere on the web.
